services:
  db:
    image: postgres:17.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: simple-sn-redis
    ports:
      - '6379:6379'
    restart: on-failure
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - '127.0.0.1:8081:8081'
    depends_on:
      - redis
    restart: on-failure

volumes:
  db-data:
